name: test

on:
  push:

jobs:
  test: 
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - run: sudo dd if=/dev/zero of=/tmp/output bs=1G count=1 oflag=dsync; rm -f /tmp/output
      - run: sudo dd if=/dev/zero of=/tmp/output bs=512 count=10k oflag=dsync; rm -f /tmp/output
