name: test

on:
  workflow_dispatch:
  schedule:
    - cron: '1/5 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        #
        ports:
          # Opens tcp port 6379 on the host and service container
          - 6379:6379
    timeout-minutes: 10
    strategy:
      matrix: 
        runner: [1,2]
    steps:
      - run: sudo dd if=/dev/zero of=/tmp/large bs=1G count=1 oflag=dsync
      - run: sudo dd if=/dev/zero of=/tmp/small bs=512 count=1000 oflag=dsync
